Repository YHJ96/codestates-study, pull requests merged in 2022-05, with the labels that each got.

#11 remove: 파일 중복 삭제
  JavaScript-Basic/소영/ArrowFunction.md
  JavaScript-Basic/소영/closure.md
  JavaScript/구조 분해 할당.md
  JavaScript/변수와 상수.md
  JavaScript/스코프.md
  JavaScript/원시자료형 참조자료형.md
  JavaScript/클로저.md
  JavaScript/타입 변환.md
  JavaScript/화살표 함수.md
Labels: 🗑 문서 삭제

#21 docs:DOM.md 작성완료 [서종렬]
  Etc/git.md
  JavaScript/서종렬/Dom.md
Labels: 📝 내용 추가

#22 docs: 3주차 공부 내용 수정
  JavaScript/README.md
Labels: 🙌 학습 목차 변경

#26 docs: 클래스 수정중 [양희준]
  JavaScript/양희준/클래스.md
Labels: 📖 내용 수정
